version: "2"

services:
  frontend:
    volumes:
      # Mount the nginx configuration.
      - ./frontend/remote/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    entrypoint: ["./frontend/remote/entrypoint.sh"]
    command: ["yarn run start:prod"]
    ports:
      - 80:80
      - 8081:8081
