/**
 * TODO: Codegen
 */
export const STATES = [
  { shortName: 'al', longName: 'Alabama' },
  { shortName: 'ak', longName: 'Alaska' },
  { shortName: 'ar', longName: 'Arkansas' },
  { shortName: 'az', longName: 'Arizona' },
  { shortName: 'ca', longName: 'California' },
  { shortName: 'co', longName: 'Colorado' },
  { shortName: 'ct', longName: 'Connecticut' },
  { shortName: 'de', longName: 'Delware' },
  { shortName: 'dc', longName: 'District of Columbia' },
  { shortName: 'fl', longName: 'Florida' },
  { shortName: 'ga', longName: 'Georgia' },
  { shortName: 'hi', longName: 'Hawaii' },
  { shortName: 'id', longName: 'Idaho' },
  { shortName: 'il', longName: 'Illinois' },
  { shortName: 'in', longName: 'Indiana' },
  { shortName: 'ia', longName: 'Iowa' },
  { shortName: 'ks', longName: 'Kansas' },
  { shortName: 'ky', longName: 'Kentucky' },
  { shortName: 'la', longName: 'Louisiana' },
  { shortName: 'me', longName: 'Maine' },
  { shortName: 'md', longName: 'Maryland' },
  { shortName: 'ma', longName: 'Massachusetts' },
  { shortName: 'mi', longName: 'Michigan' },
  { shortName: 'mn', longName: 'Minnesota' },
  { shortName: 'mo', longName: 'Missouri' },
  { shortName: 'ms', longName: 'Mississippi' },
  { shortName: 'mt', longName: 'Montana' },
  { shortName: 'ne', longName: 'Nebraska' },
  { shortName: 'nh', longName: 'New Hampshire' },
  { shortName: 'nj', longName: 'New Jersey' },
  { shortName: 'nm', longName: 'New Mexico' },
  { shortName: 'ny', longName: 'New York' },
  { shortName: 'nc', longName: 'North Carolina' },
  { shortName: 'nd', longName: 'North Dakota' },
  { shortName: 'nv', longName: 'Nevada' },
  { shortName: 'oh', longName: 'Ohio' },
  { shortName: 'ok', longName: 'Oklahoma' },
  { shortName: 'or', longName: 'Oregon' },
  { shortName: 'pa', longName: 'Pennsylvania' },
  { shortName: 'ri', longName: 'Rhode Island' },
  { shortName: 'sc', longName: 'South Carolina' },
  { shortName: 'sd', longName: 'South Dakota' },
  { shortName: 'tn', longName: 'Tennessee' },
  { shortName: 'tx', longName: 'Texas' },
  { shortName: 'ut', longName: 'Utah' },
  { shortName: 'vt', longName: 'Vermont' },
  { shortName: 'va', longName: 'Virginia' },
  { shortName: 'wa', longName: 'Washington' },
  { shortName: 'wv', longName: 'West Virginia' },
  { shortName: 'wi', longName: 'Wisconsin' },
  { shortName: 'wy', longName: 'Wyoming' },
  { shortName: 'as', longName: 'American Samoa' },
  { shortName: 'gu', longName: 'Guam' },
  { shortName: 'mp', longName: 'Northern Mariana Islands' },
  { shortName: 'pr', longName: 'Puerto Rico' },
  { shortName: 'vi', longName: 'Virgin Islands' },
]

/**
 * TODO: Codegen
 */
export type State = 'al' |'ak' |'ar' |'az' |'ca' |'co' |'ct' |'de' |'dc' |'fl' |'ga' |'hi' |'id' |'il' |'in' |'ia' |'ks' |'ky' |'la' |'me' |'md' |'ma' |'mi' |'mn' |'mo' |'ms' |'mt' |'ne' |'nh' |'nj' |'nm' |'ny' |'nc' |'nd' |'nv' |'oh' |'ok' |'or' |'pa' |'ri' |'sc' |'sd' |'tn' |'tx' |'ut' |'vt' |'va' |'wa' |'wv' |'wi' |'wy'
| 'as' | 'gu' | 'mp' | 'pr' | 'vi'

export const CaliforniaFKMServiceAreas = [
      'ca_kings_93202',
      'ca_kings_93204',
      'ca_fresno_93210',
      'ca_kings_93212',
      'ca_kings_93230',
      'ca_kings_93232',
      'ca_fresno_93234',
      'ca_kings_93239',
      'ca_fresno_93242',
      'ca_kings_93245',
      'ca_kings_93266',
      'ca_madera_93601',
      'ca_fresno_93602',
      'ca_madera_93604',
      'ca_fresno_93605',
      'ca_fresno_93606',
      'ca_fresno_93607',
      'ca_fresno_93608',
      'ca_fresno_93609',
      'ca_madera_93610',
      'ca_fresno_93611',
      'ca_fresno_93612',
      'ca_fresno_93613',
      'ca_madera_93614',
      'ca_fresno_93616',
      'ca_fresno_93619',
      'ca_fresno_93620',
      'ca_fresno_93621',
      'ca_fresno_93622',
      'ca_fresno_93624',
      'ca_fresno_93625',
      'ca_fresno_93626',
      'ca_fresno_93627',
      'ca_fresno_93628',
      'ca_fresno_93630',
      'ca_fresno_93631',
      'ca_fresno_93634',
      'ca_madera_93636',
      'ca_madera_93637',
      'ca_madera_93638',
      'ca_madera_93639',
      'ca_fresno_93640',
      'ca_fresno_93641',
      'ca_madera_93643',
      'ca_madera_93644',
      'ca_madera_93645',
      'ca_fresno_93646',
      'ca_fresno_93648',
      'ca_fresno_93649',
      'ca_fresno_93650',
      'ca_fresno_93651',
      'ca_fresno_93652',
      'ca_madera_93653',
      'ca_fresno_93654',
      'ca_fresno_93656',
      'ca_fresno_93657',
      'ca_fresno_93660',
      'ca_fresno_93662',
      'ca_fresno_93664',
      'ca_fresno_93667',
      'ca_fresno_93668',
      'ca_fresno_93675',
      'ca_fresno_93701',
      'ca_fresno_93702',
      'ca_fresno_93703',
      'ca_fresno_93704',
      'ca_fresno_93705',
      'ca_fresno_93706',
      'ca_fresno_93707',
      'ca_fresno_93708',
      'ca_fresno_93709',
      'ca_fresno_93710',
      'ca_fresno_93711',
      'ca_fresno_93712',
      'ca_fresno_93714',
      'ca_fresno_93715',
      'ca_fresno_93716',
      'ca_fresno_93717',
      'ca_fresno_93718',
      'ca_fresno_93720',
      'ca_fresno_93721',
      'ca_fresno_93722',
      'ca_fresno_93723',
      'ca_fresno_93725',
      'ca_fresno_93726',
      'ca_fresno_93727',
      'ca_fresno_93728',
      'ca_fresno_93729',
      'ca_fresno_93730',
      'ca_fresno_93737',
      'ca_fresno_93744',
      'ca_fresno_93745',
      'ca_fresno_93747',
      'ca_fresno_93755',
      'ca_fresno_93771',
      'ca_fresno_93772',
      'ca_fresno_93773',
      'ca_fresno_93774',
      'ca_fresno_93775',
      'ca_fresno_93776',
      'ca_fresno_93777',
      'ca_fresno_93778',
      'ca_fresno_93779',
      'ca_fresno_93790',
      'ca_fresno_93791',
      'ca_fresno_93792',
      'ca_fresno_93793',
      'ca_fresno_93794'
]
