/**
 * TODO: Codegen
 */
export const STATES = [
  { shortName: 'al', longName: 'Alabama' },
  { shortName: 'ak', longName: 'Alaska' },
  { shortName: 'ar', longName: 'Arkansas' },
  { shortName: 'az', longName: 'Arizona' },
  { shortName: 'ca', longName: 'California' },
  { shortName: 'co', longName: 'Colorado' },
  { shortName: 'ct', longName: 'Connecticut' },
  { shortName: 'de', longName: 'Delaware' },
  { shortName: 'dc', longName: 'District of Columbia' },
  { shortName: 'fl', longName: 'Florida' },
  { shortName: 'ga', longName: 'Georgia' },
  { shortName: 'hi', longName: 'Hawaii' },
  { shortName: 'id', longName: 'Idaho' },
  { shortName: 'il', longName: 'Illinois' },
  { shortName: 'in', longName: 'Indiana' },
  { shortName: 'ia', longName: 'Iowa' },
  { shortName: 'ks', longName: 'Kansas' },
  { shortName: 'ky', longName: 'Kentucky' },
  { shortName: 'la', longName: 'Louisiana' },
  { shortName: 'me', longName: 'Maine' },
  { shortName: 'md', longName: 'Maryland' },
  { shortName: 'ma', longName: 'Massachusetts' },
  { shortName: 'mi', longName: 'Michigan' },
  { shortName: 'mn', longName: 'Minnesota' },
  { shortName: 'mo', longName: 'Missouri' },
  { shortName: 'ms', longName: 'Mississippi' },
  { shortName: 'mt', longName: 'Montana' },
  { shortName: 'ne', longName: 'Nebraska' },
  { shortName: 'nv', longName: 'Nevada' },
  { shortName: 'nh', longName: 'New Hampshire' },
  { shortName: 'nj', longName: 'New Jersey' },
  { shortName: 'nm', longName: 'New Mexico' },
  { shortName: 'ny', longName: 'New York' },
  { shortName: 'nc', longName: 'North Carolina' },
  { shortName: 'nd', longName: 'North Dakota' },
  { shortName: 'oh', longName: 'Ohio' },
  { shortName: 'ok', longName: 'Oklahoma' },
  { shortName: 'or', longName: 'Oregon' },
  { shortName: 'pa', longName: 'Pennsylvania' },
  { shortName: 'pr', longName: 'Puerto Rico' },
  { shortName: 'ri', longName: 'Rhode Island' },
  { shortName: 'sc', longName: 'South Carolina' },
  { shortName: 'sd', longName: 'South Dakota' },
  { shortName: 'tn', longName: 'Tennessee' },
  { shortName: 'tx', longName: 'Texas' },
  { shortName: 'ut', longName: 'Utah' },
  { shortName: 'vt', longName: 'Vermont' },
  { shortName: 'va', longName: 'Virginia' },
  { shortName: 'wa', longName: 'Washington' },
  { shortName: 'wv', longName: 'West Virginia' },
  { shortName: 'wi', longName: 'Wisconsin' },
  { shortName: 'wy', longName: 'Wyoming' }
]

/**
 * TODO: Codegen
 */
export type State = 'al' | 'ak' | 'ar' | 'az' | 'ca' | 'co' | 'ct' | 'de' | 'dc' | 'fl' | 'ga' | 'hi' | 'id' | 'il' | 'in' | 'ia' | 'ks' | 'ky' | 'la' | 'me' | 'md' | 'ma' | 'mi' | 'mn' | 'mo' | 'ms' | 'mt' | 'ne' | 'nh' | 'nj' | 'nm' | 'ny' | 'nc' | 'nd' | 'nv' | 'oh' | 'ok' | 'or' | 'pa' | 'ri' | 'sc' | 'sd' | 'tn' | 'tx' | 'ut' | 'vt' | 'va' | 'wa' | 'wv' | 'wi' | 'wy' | 'pr'
