/**
 * This file was automatically generated.
 * DO NOT MODIFY IT BY HAND. Instead, run "yarn codegen" to regenerate it.
 */

import { State } from './states'

export const ZIPS_BY_COUNTY_BY_STATE: Record<
  State,
  {
    [county: string]: { zip_codes: string[]; nhcs_code: number }
  }
> = {
  cl: {
    Abejorral: { zip_codes: ['00000'], nhcs_code: NaN },
    Abrego: { zip_codes: ['00000'], nhcs_code: NaN },
    Abriaquí: { zip_codes: ['00000'], nhcs_code: NaN },
    Acacías: { zip_codes: ['00000'], nhcs_code: NaN },
    Acandí: { zip_codes: ['00000'], nhcs_code: NaN },
    Acevedo: { zip_codes: ['00000'], nhcs_code: NaN },
    Achí: { zip_codes: ['00000'], nhcs_code: NaN },
    Agrado: { zip_codes: ['00000'], nhcs_code: NaN },
    Aguachica: { zip_codes: ['00000'], nhcs_code: NaN },
    Aguada: { zip_codes: ['00000'], nhcs_code: NaN },
    Aguadas: { zip_codes: ['00000'], nhcs_code: NaN },
    'Agua de Dios': { zip_codes: ['00000'], nhcs_code: NaN },
    Aguazul: { zip_codes: ['00000'], nhcs_code: NaN },
    'Agustín Codazzi': { zip_codes: ['00000'], nhcs_code: NaN },
    Aipe: { zip_codes: ['00000'], nhcs_code: NaN },
    Albán: { zip_codes: ['00000'], nhcs_code: NaN },
    Albania: { zip_codes: ['00000'], nhcs_code: NaN },
    Alcalá: { zip_codes: ['00000'], nhcs_code: NaN },
    Aldana: { zip_codes: ['00000'], nhcs_code: NaN },
    Alejandría: { zip_codes: ['00000'], nhcs_code: NaN },
    Algeciras: { zip_codes: ['00000'], nhcs_code: NaN },
    Almaguer: { zip_codes: ['00000'], nhcs_code: NaN },
    Almeida: { zip_codes: ['00000'], nhcs_code: NaN },
    Alpujarra: { zip_codes: ['00000'], nhcs_code: NaN },
    Altamira: { zip_codes: ['00000'], nhcs_code: NaN },
    'Alto Baudó': { zip_codes: ['00000'], nhcs_code: NaN },
    'Altos del Rosario': { zip_codes: ['00000'], nhcs_code: NaN },
    Alvarado: { zip_codes: ['00000'], nhcs_code: NaN },
    Amagá: { zip_codes: ['00000'], nhcs_code: NaN },
    Amalfi: { zip_codes: ['00000'], nhcs_code: NaN },
    Ambalema: { zip_codes: ['00000'], nhcs_code: NaN },
    Anapoima: { zip_codes: ['00000'], nhcs_code: NaN },
    Ancuyá: { zip_codes: ['00000'], nhcs_code: NaN },
    Andalucía: { zip_codes: ['00000'], nhcs_code: NaN },
    Andes: { zip_codes: ['00000'], nhcs_code: NaN },
    Angelópolis: { zip_codes: ['00000'], nhcs_code: NaN },
    Angostura: { zip_codes: ['00000'], nhcs_code: NaN },
    Anolaima: { zip_codes: ['00000'], nhcs_code: NaN },
    Anorí: { zip_codes: ['00000'], nhcs_code: NaN },
    Anserma: { zip_codes: ['00000'], nhcs_code: NaN },
    Ansermanuevo: { zip_codes: ['00000'], nhcs_code: NaN },
    Anzá: { zip_codes: ['00000'], nhcs_code: NaN },
    Anzoátegui: { zip_codes: ['00000'], nhcs_code: NaN },
    Apartadó: { zip_codes: ['00000'], nhcs_code: NaN },
    Apía: { zip_codes: ['00000'], nhcs_code: NaN },
    Apulo: { zip_codes: ['00000'], nhcs_code: NaN },
    Aquitania: { zip_codes: ['00000'], nhcs_code: NaN },
    Aracataca: { zip_codes: ['00000'], nhcs_code: NaN },
    Aranzazú: { zip_codes: ['00000'], nhcs_code: NaN },
    Aratoca: { zip_codes: ['00000'], nhcs_code: NaN },
    Arauca: { zip_codes: ['00000'], nhcs_code: NaN },
    Arauquita: { zip_codes: ['00000'], nhcs_code: NaN },
    Arbeláez: { zip_codes: ['00000'], nhcs_code: NaN },
    Arboleda: { zip_codes: ['00000'], nhcs_code: NaN },
    Arboledas: { zip_codes: ['00000'], nhcs_code: NaN },
    Arboletes: { zip_codes: ['00000'], nhcs_code: NaN },
    Arcabuco: { zip_codes: ['00000'], nhcs_code: NaN },
    Argelia: { zip_codes: ['00000'], nhcs_code: NaN },
    Ariguaní: { zip_codes: ['00000'], nhcs_code: NaN },
    Arjona: { zip_codes: ['00000'], nhcs_code: NaN },
    Armenia: { zip_codes: ['00000'], nhcs_code: NaN },
    Armero: { zip_codes: ['00000'], nhcs_code: NaN },
    Astrea: { zip_codes: ['00000'], nhcs_code: NaN },
    Ataco: { zip_codes: ['00000'], nhcs_code: NaN },
    Ayapel: { zip_codes: ['00000'], nhcs_code: NaN },
    Bagadó: { zip_codes: ['00000'], nhcs_code: NaN },
    'Bahía Solano': { zip_codes: ['00000'], nhcs_code: NaN },
    'Bajo Baudó': { zip_codes: ['00000'], nhcs_code: NaN },
    Balboa: { zip_codes: ['00000'], nhcs_code: NaN },
    Baranoa: { zip_codes: ['00000'], nhcs_code: NaN },
    Baraya: { zip_codes: ['00000'], nhcs_code: NaN },
    Barbacoas: { zip_codes: ['00000'], nhcs_code: NaN },
    Barbosa: { zip_codes: ['00000'], nhcs_code: NaN },
    Barichara: { zip_codes: ['00000'], nhcs_code: NaN },
    Barrancabermeja: { zip_codes: ['00000'], nhcs_code: NaN },
    Barrancas: { zip_codes: ['00000'], nhcs_code: NaN },
    'Barranco de Loba': { zip_codes: ['00000'], nhcs_code: NaN },
    'Barranco Minas': { zip_codes: ['00000'], nhcs_code: NaN },
    Barranquilla: { zip_codes: ['00000'], nhcs_code: NaN },
    Becerril: { zip_codes: ['00000'], nhcs_code: NaN },
    Belalcázar: { zip_codes: ['00000'], nhcs_code: NaN },
    Belén: { zip_codes: ['00000'], nhcs_code: NaN },
    'Belén de los Andaquies': { zip_codes: ['00000'], nhcs_code: NaN },
    'Belén de Umbría': { zip_codes: ['00000'], nhcs_code: NaN },
    Bello: { zip_codes: ['00000'], nhcs_code: NaN },
    Belmira: { zip_codes: ['00000'], nhcs_code: NaN },
    Beltrán: { zip_codes: ['00000'], nhcs_code: NaN },
    Berbeo: { zip_codes: ['00000'], nhcs_code: NaN },
    Betania: { zip_codes: ['00000'], nhcs_code: NaN },
    Beteitiva: { zip_codes: ['00000'], nhcs_code: NaN },
    Betulia: { zip_codes: ['00000'], nhcs_code: NaN },
    Bituima: { zip_codes: ['00000'], nhcs_code: NaN },
    Boavita: { zip_codes: ['00000'], nhcs_code: NaN },
    Bochalema: { zip_codes: ['00000'], nhcs_code: NaN },
    Bojacá: { zip_codes: ['00000'], nhcs_code: NaN },
    Bojayá: { zip_codes: ['00000'], nhcs_code: NaN },
    Bolívar: { zip_codes: ['00000'], nhcs_code: NaN },
    Bosconia: { zip_codes: ['00000'], nhcs_code: NaN },
    Boyacá: { zip_codes: ['00000'], nhcs_code: NaN },
    Briceño: { zip_codes: ['00000'], nhcs_code: NaN },
    Bucaramanga: { zip_codes: ['00000'], nhcs_code: NaN },
    Bucarasica: { zip_codes: ['00000'], nhcs_code: NaN },
    Buenaventura: { zip_codes: ['00000'], nhcs_code: NaN },
    Buenavista: { zip_codes: ['00000'], nhcs_code: NaN },
    'Buenos Aires': { zip_codes: ['00000'], nhcs_code: NaN },
    Buesaco: { zip_codes: ['00000'], nhcs_code: NaN },
    Bugalagrande: { zip_codes: ['00000'], nhcs_code: NaN },
    Buriticá: { zip_codes: ['00000'], nhcs_code: NaN },
    Busbanza: { zip_codes: ['00000'], nhcs_code: NaN },
    Cabrera: { zip_codes: ['00000'], nhcs_code: NaN },
    Cabuyaro: { zip_codes: ['00000'], nhcs_code: NaN },
    Cacahual: { zip_codes: ['00000'], nhcs_code: NaN },
    Cáceres: { zip_codes: ['00000'], nhcs_code: NaN },
    Cachipay: { zip_codes: ['00000'], nhcs_code: NaN },
    Cáchira: { zip_codes: ['00000'], nhcs_code: NaN },
    Cácota: { zip_codes: ['00000'], nhcs_code: NaN },
    Caicedo: { zip_codes: ['00000'], nhcs_code: NaN },
    Caicedonia: { zip_codes: ['00000'], nhcs_code: NaN },
    Caimito: { zip_codes: ['00000'], nhcs_code: NaN },
    Cajamarca: { zip_codes: ['00000'], nhcs_code: NaN },
    Cajibío: { zip_codes: ['00000'], nhcs_code: NaN },
    Cajicá: { zip_codes: ['00000'], nhcs_code: NaN },
    Calamar: { zip_codes: ['00000'], nhcs_code: NaN },
    Calarcá: { zip_codes: ['00000'], nhcs_code: NaN },
    Caldas: { zip_codes: ['00000'], nhcs_code: NaN },
    Caldonó: { zip_codes: ['00000'], nhcs_code: NaN },
    California: { zip_codes: ['00000'], nhcs_code: NaN },
    Calima: { zip_codes: ['00000'], nhcs_code: NaN },
    Caloto: { zip_codes: ['00000'], nhcs_code: NaN },
    Campamento: { zip_codes: ['00000'], nhcs_code: NaN },
    Campoalegre: { zip_codes: ['00000'], nhcs_code: NaN },
    'Campo de la Cruz': { zip_codes: ['00000'], nhcs_code: NaN },
    Campohermoso: { zip_codes: ['00000'], nhcs_code: NaN },
    Canalete: { zip_codes: ['00000'], nhcs_code: NaN },
    Cañasgordas: { zip_codes: ['00000'], nhcs_code: NaN },
    Candelaria: { zip_codes: ['00000'], nhcs_code: NaN },
    Cantagallo: { zip_codes: ['00000'], nhcs_code: NaN },
    Caparrapí: { zip_codes: ['00000'], nhcs_code: NaN },
    Capitanejo: { zip_codes: ['00000'], nhcs_code: NaN },
    Cáqueza: { zip_codes: ['00000'], nhcs_code: NaN },
    Caracolí: { zip_codes: ['00000'], nhcs_code: NaN },
    Caramanta: { zip_codes: ['00000'], nhcs_code: NaN },
    Carcasí: { zip_codes: ['00000'], nhcs_code: NaN },
    Carepa: { zip_codes: ['00000'], nhcs_code: NaN },
    'Carmen de Carupa': { zip_codes: ['00000'], nhcs_code: NaN },
    'Carolina del Principe': { zip_codes: ['00000'], nhcs_code: NaN },
    'Cartagena de Indias': { zip_codes: ['00000'], nhcs_code: NaN },
    'Cartagena del Chairá': { zip_codes: ['00000'], nhcs_code: NaN },
    Cartago: { zip_codes: ['00000'], nhcs_code: NaN },
    Carurú: { zip_codes: ['00000'], nhcs_code: NaN },
    Casabianca: { zip_codes: ['00000'], nhcs_code: NaN },
    'Castilla la Nueva': { zip_codes: ['00000'], nhcs_code: NaN },
    Caucasia: { zip_codes: ['00000'], nhcs_code: NaN },
    Cepitá: { zip_codes: ['00000'], nhcs_code: NaN },
    Cereté: { zip_codes: ['00000'], nhcs_code: NaN },
    Cerinza: { zip_codes: ['00000'], nhcs_code: NaN },
    Cerrito: { zip_codes: ['00000'], nhcs_code: NaN },
    'Cerro de San Antonio': { zip_codes: ['00000'], nhcs_code: NaN },
    Chachagüí: { zip_codes: ['00000'], nhcs_code: NaN },
    Chaguaní: { zip_codes: ['00000'], nhcs_code: NaN },
    Chalán: { zip_codes: ['00000'], nhcs_code: NaN },
    Chámeza: { zip_codes: ['00000'], nhcs_code: NaN },
    Chaparral: { zip_codes: ['00000'], nhcs_code: NaN },
    Charalá: { zip_codes: ['00000'], nhcs_code: NaN },
    Charta: { zip_codes: ['00000'], nhcs_code: NaN },
    Chía: { zip_codes: ['00000'], nhcs_code: NaN },
    Chigorodó: { zip_codes: ['00000'], nhcs_code: NaN },
    Chimá: { zip_codes: ['00000'], nhcs_code: NaN },
    Chimichagua: { zip_codes: ['00000'], nhcs_code: NaN },
    Chinácota: { zip_codes: ['00000'], nhcs_code: NaN },
    Chinavita: { zip_codes: ['00000'], nhcs_code: NaN },
    Chinchiná: { zip_codes: ['00000'], nhcs_code: NaN },
    Chinú: { zip_codes: ['00000'], nhcs_code: NaN },
    Chipaque: { zip_codes: ['00000'], nhcs_code: NaN },
    Chipatá: { zip_codes: ['00000'], nhcs_code: NaN },
    Chiquinquirá: { zip_codes: ['00000'], nhcs_code: NaN },
    Chíquiza: { zip_codes: ['00000'], nhcs_code: NaN },
    Chiriguaná: { zip_codes: ['00000'], nhcs_code: NaN },
    Chiscas: { zip_codes: ['00000'], nhcs_code: NaN },
    Chita: { zip_codes: ['00000'], nhcs_code: NaN },
    Chitagá: { zip_codes: ['00000'], nhcs_code: NaN },
    Chitaraque: { zip_codes: ['00000'], nhcs_code: NaN },
    Chivatá: { zip_codes: ['00000'], nhcs_code: NaN },
    Chivolo: { zip_codes: ['00000'], nhcs_code: NaN },
    Chivor: { zip_codes: ['00000'], nhcs_code: NaN },
    Choachí: { zip_codes: ['00000'], nhcs_code: NaN },
    Chocontá: { zip_codes: ['00000'], nhcs_code: NaN },
    Cicuco: { zip_codes: ['00000'], nhcs_code: NaN },
    Ciénaga: { zip_codes: ['00000'], nhcs_code: NaN },
    'Ciénaga de Oro': { zip_codes: ['00000'], nhcs_code: NaN },
    Cimitarra: { zip_codes: ['00000'], nhcs_code: NaN },
    Circasia: { zip_codes: ['00000'], nhcs_code: NaN },
    Cisneros: { zip_codes: ['00000'], nhcs_code: NaN },
    Cocorná: { zip_codes: ['00000'], nhcs_code: NaN },
    Coello: { zip_codes: ['00000'], nhcs_code: NaN },
    Cogua: { zip_codes: ['00000'], nhcs_code: NaN },
    Colombia: { zip_codes: ['00000'], nhcs_code: NaN },
    Colón: { zip_codes: ['00000'], nhcs_code: NaN },
    Colosó: { zip_codes: ['00000'], nhcs_code: NaN },
    Cómbita: { zip_codes: ['00000'], nhcs_code: NaN },
    Concepción: { zip_codes: ['00000'], nhcs_code: NaN },
    Concordia: { zip_codes: ['00000'], nhcs_code: NaN },
    Condoto: { zip_codes: ['00000'], nhcs_code: NaN },
    Confines: { zip_codes: ['00000'], nhcs_code: NaN },
    Consacá: { zip_codes: ['00000'], nhcs_code: NaN },
    Contadero: { zip_codes: ['00000'], nhcs_code: NaN },
    Contratación: { zip_codes: ['00000'], nhcs_code: NaN },
    Convención: { zip_codes: ['00000'], nhcs_code: NaN },
    Copacabana: { zip_codes: ['00000'], nhcs_code: NaN },
    Coper: { zip_codes: ['00000'], nhcs_code: NaN },
    Córdoba: { zip_codes: ['00000'], nhcs_code: NaN },
    Corinto: { zip_codes: ['00000'], nhcs_code: NaN },
    Coromoro: { zip_codes: ['00000'], nhcs_code: NaN },
    Corozal: { zip_codes: ['00000'], nhcs_code: NaN },
    Corrales: { zip_codes: ['00000'], nhcs_code: NaN },
    Cota: { zip_codes: ['00000'], nhcs_code: NaN },
    Covarachía: { zip_codes: ['00000'], nhcs_code: NaN },
    Coyaima: { zip_codes: ['00000'], nhcs_code: NaN },
    'Cravo Norte': { zip_codes: ['00000'], nhcs_code: NaN },
    Cuaspud: { zip_codes: ['00000'], nhcs_code: NaN },
    Cubará: { zip_codes: ['00000'], nhcs_code: NaN },
    Cucaita: { zip_codes: ['00000'], nhcs_code: NaN },
    Cucunubá: { zip_codes: ['00000'], nhcs_code: NaN },
    Cucutilla: { zip_codes: ['00000'], nhcs_code: NaN },
    Cuítiva: { zip_codes: ['00000'], nhcs_code: NaN },
    Cumaral: { zip_codes: ['00000'], nhcs_code: NaN },
    Cumaribo: { zip_codes: ['00000'], nhcs_code: NaN },
    Cumbal: { zip_codes: ['00000'], nhcs_code: NaN },
    Cumbitara: { zip_codes: ['00000'], nhcs_code: NaN },
    Cunday: { zip_codes: ['00000'], nhcs_code: NaN },
    Curillo: { zip_codes: ['00000'], nhcs_code: NaN },
    Curití: { zip_codes: ['00000'], nhcs_code: NaN },
    Curumaní: { zip_codes: ['00000'], nhcs_code: NaN },
    Dabeiba: { zip_codes: ['00000'], nhcs_code: NaN },
    Dagua: { zip_codes: ['00000'], nhcs_code: NaN },
    Dolores: { zip_codes: ['00000'], nhcs_code: NaN },
    'Don Matías': { zip_codes: ['00000'], nhcs_code: NaN },
    Dosquebradas: { zip_codes: ['00000'], nhcs_code: NaN },
    Duitama: { zip_codes: ['00000'], nhcs_code: NaN },
    Durania: { zip_codes: ['00000'], nhcs_code: NaN },
    Ebéjico: { zip_codes: ['00000'], nhcs_code: NaN },
    'El Águila': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Bagre': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Banco': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Calvario': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Cantón del San Pablo': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Carmen': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Carmen de Atrato': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Carmen de Bolívar': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Carmen de Chucurí': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Carmen de Viboral': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Castillo': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Cerrito': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Charco': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Cocuy': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Colegio': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Copey': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Doncello': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Dorado': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Dovio': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Encanto': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Espino': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Guacamayo': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Guamo': { zip_codes: ['00000'], nhcs_code: NaN },
    Elías: { zip_codes: ['00000'], nhcs_code: NaN },
    'El Litoral del San Juan': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Paso': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Paujíl': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Peñon': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Piñón': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Playón': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Retorno': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Rosario': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Santuario': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Tablón de Gomez': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Tambo': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Tarra': { zip_codes: ['00000'], nhcs_code: NaN },
    'El Zulia': { zip_codes: ['00000'], nhcs_code: NaN },
    Encino: { zip_codes: ['00000'], nhcs_code: NaN },
    Enciso: { zip_codes: ['00000'], nhcs_code: NaN },
    Entrerríos: { zip_codes: ['00000'], nhcs_code: NaN },
    Envigado: { zip_codes: ['00000'], nhcs_code: NaN },
    Espinal: { zip_codes: ['00000'], nhcs_code: NaN },
    Facatativá: { zip_codes: ['00000'], nhcs_code: NaN },
    Falán: { zip_codes: ['00000'], nhcs_code: NaN },
    Filadelfia: { zip_codes: ['00000'], nhcs_code: NaN },
    Filandia: { zip_codes: ['00000'], nhcs_code: NaN },
    Firavitoba: { zip_codes: ['00000'], nhcs_code: NaN },
    Flandes: { zip_codes: ['00000'], nhcs_code: NaN },
    Florencia: { zip_codes: ['00000'], nhcs_code: NaN },
    Floresta: { zip_codes: ['00000'], nhcs_code: NaN },
    Florián: { zip_codes: ['00000'], nhcs_code: NaN },
    Florida: { zip_codes: ['00000'], nhcs_code: NaN },
    Floridablanca: { zip_codes: ['00000'], nhcs_code: NaN },
    Fómeque: { zip_codes: ['00000'], nhcs_code: NaN },
    Fonseca: { zip_codes: ['00000'], nhcs_code: NaN },
    Fortul: { zip_codes: ['00000'], nhcs_code: NaN },
    Fosca: { zip_codes: ['00000'], nhcs_code: NaN },
    'Francisco Pizarro': { zip_codes: ['00000'], nhcs_code: NaN },
    Fredonia: { zip_codes: ['00000'], nhcs_code: NaN },
    Fresno: { zip_codes: ['00000'], nhcs_code: NaN },
    Frontino: { zip_codes: ['00000'], nhcs_code: NaN },
    'Fuente de Oro': { zip_codes: ['00000'], nhcs_code: NaN },
    Fundación: { zip_codes: ['00000'], nhcs_code: NaN },
    Funes: { zip_codes: ['00000'], nhcs_code: NaN },
    Funza: { zip_codes: ['00000'], nhcs_code: NaN },
    Fúquene: { zip_codes: ['00000'], nhcs_code: NaN },
    Fusagasugá: { zip_codes: ['00000'], nhcs_code: NaN },
    Gachalá: { zip_codes: ['00000'], nhcs_code: NaN },
    Gachancipá: { zip_codes: ['00000'], nhcs_code: NaN },
    Gachantivá: { zip_codes: ['00000'], nhcs_code: NaN },
    Gachetá: { zip_codes: ['00000'], nhcs_code: NaN },
    Galán: { zip_codes: ['00000'], nhcs_code: NaN },
    Galapa: { zip_codes: ['00000'], nhcs_code: NaN },
    Galeras: { zip_codes: ['00000'], nhcs_code: NaN },
    Gamarra: { zip_codes: ['00000'], nhcs_code: NaN },
    Gámbita: { zip_codes: ['00000'], nhcs_code: NaN },
    Gámeza: { zip_codes: ['00000'], nhcs_code: NaN },
    Garagoa: { zip_codes: ['00000'], nhcs_code: NaN },
    Garzón: { zip_codes: ['00000'], nhcs_code: NaN },
    Génova: { zip_codes: ['00000'], nhcs_code: NaN },
    Gigante: { zip_codes: ['00000'], nhcs_code: NaN },
    Ginebra: { zip_codes: ['00000'], nhcs_code: NaN },
    Giraldo: { zip_codes: ['00000'], nhcs_code: NaN },
    Girardot: { zip_codes: ['00000'], nhcs_code: NaN },
    Girardota: { zip_codes: ['00000'], nhcs_code: NaN },
    Girón: { zip_codes: ['00000'], nhcs_code: NaN },
    'Gómez Plata': { zip_codes: ['00000'], nhcs_code: NaN },
    González: { zip_codes: ['00000'], nhcs_code: NaN },
    Gramalote: { zip_codes: ['00000'], nhcs_code: NaN },
    Granada: { zip_codes: ['00000'], nhcs_code: NaN },
    Guaca: { zip_codes: ['00000'], nhcs_code: NaN },
    Guacamayas: { zip_codes: ['00000'], nhcs_code: NaN },
    Guacarí: { zip_codes: ['00000'], nhcs_code: NaN },
    Guachetá: { zip_codes: ['00000'], nhcs_code: NaN },
    Guachucal: { zip_codes: ['00000'], nhcs_code: NaN },
    'Guadalajara de Buga': { zip_codes: ['00000'], nhcs_code: NaN },
    Guadalupe: { zip_codes: ['00000'], nhcs_code: NaN },
    Guaduas: { zip_codes: ['00000'], nhcs_code: NaN },
    Guaitarilla: { zip_codes: ['00000'], nhcs_code: NaN },
    Gualmatán: { zip_codes: ['00000'], nhcs_code: NaN },
    Guamal: { zip_codes: ['00000'], nhcs_code: NaN },
    Guamo: { zip_codes: ['00000'], nhcs_code: NaN },
    Guapí: { zip_codes: ['00000'], nhcs_code: NaN },
    Guapotá: { zip_codes: ['00000'], nhcs_code: NaN },
    Guarandá: { zip_codes: ['00000'], nhcs_code: NaN },
    Guarne: { zip_codes: ['00000'], nhcs_code: NaN },
    Guasca: { zip_codes: ['00000'], nhcs_code: NaN },
    Guatapé: { zip_codes: ['00000'], nhcs_code: NaN },
    Guataquí: { zip_codes: ['00000'], nhcs_code: NaN },
    Guatavita: { zip_codes: ['00000'], nhcs_code: NaN },
    Guateque: { zip_codes: ['00000'], nhcs_code: NaN },
    Guática: { zip_codes: ['00000'], nhcs_code: NaN },
    Guavatá: { zip_codes: ['00000'], nhcs_code: NaN },
    'Guayabal de Síquima': { zip_codes: ['00000'], nhcs_code: NaN },
    Guayabetal: { zip_codes: ['00000'], nhcs_code: NaN },
    Guayatá: { zip_codes: ['00000'], nhcs_code: NaN },
    Güepsa: { zip_codes: ['00000'], nhcs_code: NaN },
    Guicán: { zip_codes: ['00000'], nhcs_code: NaN },
    Gutiérrez: { zip_codes: ['00000'], nhcs_code: NaN },
    Hacarí: { zip_codes: ['00000'], nhcs_code: NaN },
    'Hatillo de Loba': { zip_codes: ['00000'], nhcs_code: NaN },
    Hato: { zip_codes: ['00000'], nhcs_code: NaN },
    'Hato Corozal': { zip_codes: ['00000'], nhcs_code: NaN },
    Heliconia: { zip_codes: ['00000'], nhcs_code: NaN },
    Herrán: { zip_codes: ['00000'], nhcs_code: NaN },
    Herveo: { zip_codes: ['00000'], nhcs_code: NaN },
    Hispania: { zip_codes: ['00000'], nhcs_code: NaN },
    Hobo: { zip_codes: ['00000'], nhcs_code: NaN },
    Honda: { zip_codes: ['00000'], nhcs_code: NaN },
    Ibagué: { zip_codes: ['00000'], nhcs_code: NaN },
    Icononzo: { zip_codes: ['00000'], nhcs_code: NaN },
    Iles: { zip_codes: ['00000'], nhcs_code: NaN },
    Imués: { zip_codes: ['00000'], nhcs_code: NaN },
    Inzá: { zip_codes: ['00000'], nhcs_code: NaN },
    Ipiales: { zip_codes: ['00000'], nhcs_code: NaN },
    Iquira: { zip_codes: ['00000'], nhcs_code: NaN },
    Isnos: { zip_codes: ['00000'], nhcs_code: NaN },
    Istmina: { zip_codes: ['00000'], nhcs_code: NaN },
    Itagüí: { zip_codes: ['00000'], nhcs_code: NaN },
    Ituango: { zip_codes: ['00000'], nhcs_code: NaN },
    Izá: { zip_codes: ['00000'], nhcs_code: NaN },
    Jambaló: { zip_codes: ['00000'], nhcs_code: NaN },
    Jamundí: { zip_codes: ['00000'], nhcs_code: NaN },
    Jardín: { zip_codes: ['00000'], nhcs_code: NaN },
    Jenesano: { zip_codes: ['00000'], nhcs_code: NaN },
    Jericó: { zip_codes: ['00000'], nhcs_code: NaN },
    Jerusalén: { zip_codes: ['00000'], nhcs_code: NaN },
    'Jesús María': { zip_codes: ['00000'], nhcs_code: NaN },
    Jordán: { zip_codes: ['00000'], nhcs_code: NaN },
    'Juan de Acosta': { zip_codes: ['00000'], nhcs_code: NaN },
    Junín: { zip_codes: ['00000'], nhcs_code: NaN },
    'La Argentina': { zip_codes: ['00000'], nhcs_code: NaN },
    Labateca: { zip_codes: ['00000'], nhcs_code: NaN },
    'La Belleza': { zip_codes: ['00000'], nhcs_code: NaN },
    Labranzagrande: { zip_codes: ['00000'], nhcs_code: NaN },
    'La Calera': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Capilla': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Ceja': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Chorrera': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Cruz': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Cumbre': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Dorada': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Esperanza': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Estrella': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Florida': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Gloria': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Jagua de Ibirico': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Llanada': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Macarena': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Merced': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Mesa': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Montañita': { zip_codes: ['00000'], nhcs_code: NaN },
    Landázuri: { zip_codes: ['00000'], nhcs_code: NaN },
    'La Palma': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Paz': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Pedrera': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Peña': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Plata': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Playa de Belén': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Primavera': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Salina': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Sierra': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Tebaida': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Tola': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Unión de Sucre': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Uribe': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Uvita': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Vega': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Victoria': { zip_codes: ['00000'], nhcs_code: NaN },
    'La Virginia': { zip_codes: ['00000'], nhcs_code: NaN },
    Lebrija: { zip_codes: ['00000'], nhcs_code: NaN },
    Leiva: { zip_codes: ['00000'], nhcs_code: NaN },
    Lejanías: { zip_codes: ['00000'], nhcs_code: NaN },
    Lenguazaque: { zip_codes: ['00000'], nhcs_code: NaN },
    Lérida: { zip_codes: ['00000'], nhcs_code: NaN },
    Leticia: { zip_codes: ['00000'], nhcs_code: NaN },
    Líbano: { zip_codes: ['00000'], nhcs_code: NaN },
    Liborina: { zip_codes: ['00000'], nhcs_code: NaN },
    Linares: { zip_codes: ['00000'], nhcs_code: NaN },
    Lloró: { zip_codes: ['00000'], nhcs_code: NaN },
    'López de Micay': { zip_codes: ['00000'], nhcs_code: NaN },
    'Los Andes': { zip_codes: ['00000'], nhcs_code: NaN },
    'Los Córdobas': { zip_codes: ['00000'], nhcs_code: NaN },
    'Los Palmitos': { zip_codes: ['00000'], nhcs_code: NaN },
    'Los Patios': { zip_codes: ['00000'], nhcs_code: NaN },
    'Los Santos': { zip_codes: ['00000'], nhcs_code: NaN },
    Lourdes: { zip_codes: ['00000'], nhcs_code: NaN },
    Luruaco: { zip_codes: ['00000'], nhcs_code: NaN },
    Macanal: { zip_codes: ['00000'], nhcs_code: NaN },
    Macaravita: { zip_codes: ['00000'], nhcs_code: NaN },
    Maceo: { zip_codes: ['00000'], nhcs_code: NaN },
    Machetá: { zip_codes: ['00000'], nhcs_code: NaN },
    Madrid: { zip_codes: ['00000'], nhcs_code: NaN },
    Magüí: { zip_codes: ['00000'], nhcs_code: NaN },
    Mahates: { zip_codes: ['00000'], nhcs_code: NaN },
    Maicao: { zip_codes: ['00000'], nhcs_code: NaN },
    Majagual: { zip_codes: ['00000'], nhcs_code: NaN },
    Malambo: { zip_codes: ['00000'], nhcs_code: NaN },
    Mallama: { zip_codes: ['00000'], nhcs_code: NaN },
    Manatí: { zip_codes: ['00000'], nhcs_code: NaN },
    Manaure: { zip_codes: ['00000'], nhcs_code: NaN },
    Maní: { zip_codes: ['00000'], nhcs_code: NaN },
    Manizales: { zip_codes: ['00000'], nhcs_code: NaN },
    Manta: { zip_codes: ['00000'], nhcs_code: NaN },
    Manzanares: { zip_codes: ['00000'], nhcs_code: NaN },
    Mapiripán: { zip_codes: ['00000'], nhcs_code: NaN },
    Margarita: { zip_codes: ['00000'], nhcs_code: NaN },
    'María la Baja': { zip_codes: ['00000'], nhcs_code: NaN },
    Marinilla: { zip_codes: ['00000'], nhcs_code: NaN },
    Maripí: { zip_codes: ['00000'], nhcs_code: NaN },
    Marmato: { zip_codes: ['00000'], nhcs_code: NaN },
    Marquetalia: { zip_codes: ['00000'], nhcs_code: NaN },
    Marsella: { zip_codes: ['00000'], nhcs_code: NaN },
    Marulanda: { zip_codes: ['00000'], nhcs_code: NaN },
    Matanza: { zip_codes: ['00000'], nhcs_code: NaN },
    Medellín: { zip_codes: ['00000'], nhcs_code: NaN },
    Medina: { zip_codes: ['00000'], nhcs_code: NaN },
    Melgar: { zip_codes: ['00000'], nhcs_code: NaN },
    Mercaderes: { zip_codes: ['00000'], nhcs_code: NaN },
    Mesetas: { zip_codes: ['00000'], nhcs_code: NaN },
    Milán: { zip_codes: ['00000'], nhcs_code: NaN },
    Miraflores: { zip_codes: ['00000'], nhcs_code: NaN },
    Miranda: { zip_codes: ['00000'], nhcs_code: NaN },
    'Mirití-Paraná': { zip_codes: ['00000'], nhcs_code: NaN },
    Mistrato: { zip_codes: ['00000'], nhcs_code: NaN },
    Mitú: { zip_codes: ['00000'], nhcs_code: NaN },
    Mogotes: { zip_codes: ['00000'], nhcs_code: NaN },
    Molagavita: { zip_codes: ['00000'], nhcs_code: NaN },
    Momil: { zip_codes: ['00000'], nhcs_code: NaN },
    Mompós: { zip_codes: ['00000'], nhcs_code: NaN },
    Mongua: { zip_codes: ['00000'], nhcs_code: NaN },
    Monguí: { zip_codes: ['00000'], nhcs_code: NaN },
    Moniquirá: { zip_codes: ['00000'], nhcs_code: NaN },
    Moñitos: { zip_codes: ['00000'], nhcs_code: NaN },
    Montebello: { zip_codes: ['00000'], nhcs_code: NaN },
    Montecristo: { zip_codes: ['00000'], nhcs_code: NaN },
    Montelíbano: { zip_codes: ['00000'], nhcs_code: NaN },
    Montenegro: { zip_codes: ['00000'], nhcs_code: NaN },
    Montería: { zip_codes: ['00000'], nhcs_code: NaN },
    Monterrey: { zip_codes: ['00000'], nhcs_code: NaN },
    Morales: { zip_codes: ['00000'], nhcs_code: NaN },
    Morelia: { zip_codes: ['00000'], nhcs_code: NaN },
    Morroa: { zip_codes: ['00000'], nhcs_code: NaN },
    Mosquera: { zip_codes: ['00000'], nhcs_code: NaN },
    Motavita: { zip_codes: ['00000'], nhcs_code: NaN },
    Murillo: { zip_codes: ['00000'], nhcs_code: NaN },
    Murindó: { zip_codes: ['00000'], nhcs_code: NaN },
    Mutatá: { zip_codes: ['00000'], nhcs_code: NaN },
    Mutiscua: { zip_codes: ['00000'], nhcs_code: NaN },
    Muzo: { zip_codes: ['00000'], nhcs_code: NaN },
    Nariño: { zip_codes: ['00000'], nhcs_code: NaN },
    Nátaga: { zip_codes: ['00000'], nhcs_code: NaN },
    Natagaima: { zip_codes: ['00000'], nhcs_code: NaN },
    Nechí: { zip_codes: ['00000'], nhcs_code: NaN },
    Necoclí: { zip_codes: ['00000'], nhcs_code: NaN },
    Neira: { zip_codes: ['00000'], nhcs_code: NaN },
    Neiva: { zip_codes: ['00000'], nhcs_code: NaN },
    Nemocón: { zip_codes: ['00000'], nhcs_code: NaN },
    Nilo: { zip_codes: ['00000'], nhcs_code: NaN },
    Nimaima: { zip_codes: ['00000'], nhcs_code: NaN },
    Nobsa: { zip_codes: ['00000'], nhcs_code: NaN },
    Nocaima: { zip_codes: ['00000'], nhcs_code: NaN },
    Novita: { zip_codes: ['00000'], nhcs_code: NaN },
    'Nuevo Colón': { zip_codes: ['00000'], nhcs_code: NaN },
    Nunchía: { zip_codes: ['00000'], nhcs_code: NaN },
    Nuquí: { zip_codes: ['00000'], nhcs_code: NaN },
    Obando: { zip_codes: ['00000'], nhcs_code: NaN },
    Ocamonte: { zip_codes: ['00000'], nhcs_code: NaN },
    Ocaña: { zip_codes: ['00000'], nhcs_code: NaN },
    Oiba: { zip_codes: ['00000'], nhcs_code: NaN },
    Oicatá: { zip_codes: ['00000'], nhcs_code: NaN },
    Olaya: { zip_codes: ['00000'], nhcs_code: NaN },
    'Olaya Herrera': { zip_codes: ['00000'], nhcs_code: NaN },
    Onzaga: { zip_codes: ['00000'], nhcs_code: NaN },
    Oporapa: { zip_codes: ['00000'], nhcs_code: NaN },
    Orito: { zip_codes: ['00000'], nhcs_code: NaN },
    Orocué: { zip_codes: ['00000'], nhcs_code: NaN },
    Ortega: { zip_codes: ['00000'], nhcs_code: NaN },
    Ospina: { zip_codes: ['00000'], nhcs_code: NaN },
    Otanche: { zip_codes: ['00000'], nhcs_code: NaN },
    Ovejas: { zip_codes: ['00000'], nhcs_code: NaN },
    Pachavita: { zip_codes: ['00000'], nhcs_code: NaN },
    Pacho: { zip_codes: ['00000'], nhcs_code: NaN },
    Pacoa: { zip_codes: ['00000'], nhcs_code: NaN },
    Pácora: { zip_codes: ['00000'], nhcs_code: NaN },
    Padilla: { zip_codes: ['00000'], nhcs_code: NaN },
    Páez: { zip_codes: ['00000'], nhcs_code: NaN },
    Paicol: { zip_codes: ['00000'], nhcs_code: NaN },
    Pailitas: { zip_codes: ['00000'], nhcs_code: NaN },
    Paime: { zip_codes: ['00000'], nhcs_code: NaN },
    Paipa: { zip_codes: ['00000'], nhcs_code: NaN },
    Pajarito: { zip_codes: ['00000'], nhcs_code: NaN },
    Palermo: { zip_codes: ['00000'], nhcs_code: NaN },
    Palestina: { zip_codes: ['00000'], nhcs_code: NaN },
    'Palmar de Varela': { zip_codes: ['00000'], nhcs_code: NaN },
    'Palmas del Socorro': { zip_codes: ['00000'], nhcs_code: NaN },
    Palmira: { zip_codes: ['00000'], nhcs_code: NaN },
    Pamplona: { zip_codes: ['00000'], nhcs_code: NaN },
    Pamplonita: { zip_codes: ['00000'], nhcs_code: NaN },
    'Pana Pana': { zip_codes: ['00000'], nhcs_code: NaN },
    Pandi: { zip_codes: ['00000'], nhcs_code: NaN },
    Panqueba: { zip_codes: ['00000'], nhcs_code: NaN },
    Páramo: { zip_codes: ['00000'], nhcs_code: NaN },
    Paratebueno: { zip_codes: ['00000'], nhcs_code: NaN },
    Pasca: { zip_codes: ['00000'], nhcs_code: NaN },
    Patía: { zip_codes: ['00000'], nhcs_code: NaN },
    Pauna: { zip_codes: ['00000'], nhcs_code: NaN },
    Paya: { zip_codes: ['00000'], nhcs_code: NaN },
    'Paz de Ariporo': { zip_codes: ['00000'], nhcs_code: NaN },
    'Paz de Río': { zip_codes: ['00000'], nhcs_code: NaN },
    Pedraza: { zip_codes: ['00000'], nhcs_code: NaN },
    Pelaya: { zip_codes: ['00000'], nhcs_code: NaN },
    Peñol: { zip_codes: ['00000'], nhcs_code: NaN },
    Pensilvania: { zip_codes: ['00000'], nhcs_code: NaN },
    Pequé: { zip_codes: ['00000'], nhcs_code: NaN },
    Pereira: { zip_codes: ['00000'], nhcs_code: NaN },
    Pesca: { zip_codes: ['00000'], nhcs_code: NaN },
    Piedecuesta: { zip_codes: ['00000'], nhcs_code: NaN },
    Piedras: { zip_codes: ['00000'], nhcs_code: NaN },
    Piendamó: { zip_codes: ['00000'], nhcs_code: NaN },
    Pijao: { zip_codes: ['00000'], nhcs_code: NaN },
    Pinchote: { zip_codes: ['00000'], nhcs_code: NaN },
    Pinillos: { zip_codes: ['00000'], nhcs_code: NaN },
    Piojó: { zip_codes: ['00000'], nhcs_code: NaN },
    Pisba: { zip_codes: ['00000'], nhcs_code: NaN },
    Pital: { zip_codes: ['00000'], nhcs_code: NaN },
    Pitalito: { zip_codes: ['00000'], nhcs_code: NaN },
    Pivijay: { zip_codes: ['00000'], nhcs_code: NaN },
    Planadas: { zip_codes: ['00000'], nhcs_code: NaN },
    'Planeta Rica': { zip_codes: ['00000'], nhcs_code: NaN },
    Plato: { zip_codes: ['00000'], nhcs_code: NaN },
    Policarpa: { zip_codes: ['00000'], nhcs_code: NaN },
    Polonuevo: { zip_codes: ['00000'], nhcs_code: NaN },
    Ponedera: { zip_codes: ['00000'], nhcs_code: NaN },
    Popayán: { zip_codes: ['00000'], nhcs_code: NaN },
    Pore: { zip_codes: ['00000'], nhcs_code: NaN },
    Potosí: { zip_codes: ['00000'], nhcs_code: NaN },
    Pradera: { zip_codes: ['00000'], nhcs_code: NaN },
    Prado: { zip_codes: ['00000'], nhcs_code: NaN },
    Providencia: { zip_codes: ['00000'], nhcs_code: NaN },
    'Pueblo Nuevo': { zip_codes: ['00000'], nhcs_code: NaN },
    'Pueblo Rico': { zip_codes: ['00000'], nhcs_code: NaN },
    Pueblorrico: { zip_codes: ['00000'], nhcs_code: NaN },
    'Pueblo Viejo': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puente Nacional': { zip_codes: ['00000'], nhcs_code: NaN },
    Puerres: { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Asís': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Berrío': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Boyacá': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Caicedo': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Carreño': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Colombia': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Concordia': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Escondido': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Gaitán': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Guzmán': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Inírida': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Leguízamo': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Libertador': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Lleras': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto López': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Nare': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Nariño': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Parra': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Rico': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Rondón': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Salgar': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Santander': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Tejada': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Triunfo': { zip_codes: ['00000'], nhcs_code: NaN },
    'Puerto Wilches': { zip_codes: ['00000'], nhcs_code: NaN },
    Pulí: { zip_codes: ['00000'], nhcs_code: NaN },
    Pupiales: { zip_codes: ['00000'], nhcs_code: NaN },
    Puracé: { zip_codes: ['00000'], nhcs_code: NaN },
    Purificación: { zip_codes: ['00000'], nhcs_code: NaN },
    Purísima: { zip_codes: ['00000'], nhcs_code: NaN },
    Quebradanegra: { zip_codes: ['00000'], nhcs_code: NaN },
    Quetame: { zip_codes: ['00000'], nhcs_code: NaN },
    Quibdó: { zip_codes: ['00000'], nhcs_code: NaN },
    Quimbaya: { zip_codes: ['00000'], nhcs_code: NaN },
    Quinchía: { zip_codes: ['00000'], nhcs_code: NaN },
    Quípama: { zip_codes: ['00000'], nhcs_code: NaN },
    Quipile: { zip_codes: ['00000'], nhcs_code: NaN },
    Ragonvalia: { zip_codes: ['00000'], nhcs_code: NaN },
    Ramiriquí: { zip_codes: ['00000'], nhcs_code: NaN },
    Ráquira: { zip_codes: ['00000'], nhcs_code: NaN },
    Recetor: { zip_codes: ['00000'], nhcs_code: NaN },
    Remedios: { zip_codes: ['00000'], nhcs_code: NaN },
    Remolino: { zip_codes: ['00000'], nhcs_code: NaN },
    Repelón: { zip_codes: ['00000'], nhcs_code: NaN },
    Restrepo: { zip_codes: ['00000'], nhcs_code: NaN },
    Retiro: { zip_codes: ['00000'], nhcs_code: NaN },
    Ricaurte: { zip_codes: ['00000'], nhcs_code: NaN },
    Rioblanco: { zip_codes: ['00000'], nhcs_code: NaN },
    'Río de Oro': { zip_codes: ['00000'], nhcs_code: NaN },
    Riofrío: { zip_codes: ['00000'], nhcs_code: NaN },
    Riohacha: { zip_codes: ['00000'], nhcs_code: NaN },
    Rionegro: { zip_codes: ['00000'], nhcs_code: NaN },
    Riosucio: { zip_codes: ['00000'], nhcs_code: NaN },
    'Río Viejo': { zip_codes: ['00000'], nhcs_code: NaN },
    Risaralda: { zip_codes: ['00000'], nhcs_code: NaN },
    Rivera: { zip_codes: ['00000'], nhcs_code: NaN },
    'Roberto Payán': { zip_codes: ['00000'], nhcs_code: NaN },
    Roldanillo: { zip_codes: ['00000'], nhcs_code: NaN },
    Roncesvalles: { zip_codes: ['00000'], nhcs_code: NaN },
    Rondón: { zip_codes: ['00000'], nhcs_code: NaN },
    Rosas: { zip_codes: ['00000'], nhcs_code: NaN },
    Rovira: { zip_codes: ['00000'], nhcs_code: NaN },
    'Sabana de Torres': { zip_codes: ['00000'], nhcs_code: NaN },
    Sabanagrande: { zip_codes: ['00000'], nhcs_code: NaN },
    Sabanalarga: { zip_codes: ['00000'], nhcs_code: NaN },
    Sabaneta: { zip_codes: ['00000'], nhcs_code: NaN },
    Saboyá: { zip_codes: ['00000'], nhcs_code: NaN },
    Sáchica: { zip_codes: ['00000'], nhcs_code: NaN },
    Saladoblanco: { zip_codes: ['00000'], nhcs_code: NaN },
    Salamina: { zip_codes: ['00000'], nhcs_code: NaN },
    'Salazar de las Palmas': { zip_codes: ['00000'], nhcs_code: NaN },
    Saldaña: { zip_codes: ['00000'], nhcs_code: NaN },
    Salento: { zip_codes: ['00000'], nhcs_code: NaN },
    Salgar: { zip_codes: ['00000'], nhcs_code: NaN },
    Samacá: { zip_codes: ['00000'], nhcs_code: NaN },
    Samaná: { zip_codes: ['00000'], nhcs_code: NaN },
    Samaniego: { zip_codes: ['00000'], nhcs_code: NaN },
    Sampués: { zip_codes: ['00000'], nhcs_code: NaN },
    'San Agustín': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Alberto': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Andrés': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Andrés de Cuerquia': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Andrés de Sotavento': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Antero': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Antonio': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Antonio del Tequendama': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Antonio de Palmito': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Benito': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Benito Abad': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Bernardino de Sahagún': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Bernardo': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Bernardo del Viento': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Calixto': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Carlos': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Carlos de Guaroa': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Cayetano': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Diego': { zip_codes: ['00000'], nhcs_code: NaN },
    Sandoná: { zip_codes: ['00000'], nhcs_code: NaN },
    'San Eduardo': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Estanislao de Kostka': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Felipe': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Fernando': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Francisco': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Gil': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Jacinto': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Jerónimo': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Joaquín': { zip_codes: ['00000'], nhcs_code: NaN },
    'San José de Cúcuta': { zip_codes: ['00000'], nhcs_code: NaN },
    'San José de la Montaña': { zip_codes: ['00000'], nhcs_code: NaN },
    'San José del Fragua': { zip_codes: ['00000'], nhcs_code: NaN },
    'San José del Guaviare': { zip_codes: ['00000'], nhcs_code: NaN },
    'San José del Palmar': { zip_codes: ['00000'], nhcs_code: NaN },
    'San José de Miranda': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Jose de Ocune': { zip_codes: ['00000'], nhcs_code: NaN },
    'San José de Pare': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Juan de Arama': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Juan de Betulia': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Juan del Cesar': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Juan de Pasto': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Juan de Río Seco': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Juan de Urabá': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Juanito': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Juan Nepomuceno': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Lorenzo': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Luis': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Luís': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Luis de Cubarral': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Luis de Gaceno': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Luis de Palenque': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Marcos': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Martín': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Martín de Loba': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Mateo': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Miguel': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Miguel de Mocoa': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Miguel de Sema': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Onofre': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Pablo': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Pablo de Borbur': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Pedro': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Pedro de Cartago': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Pedro de los Milagros': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Pedro de Urabá': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Pelayo': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Rafael': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Roque': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Sebastián': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Sebastián de Buenavista': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Sebastian de Mariquita': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Ana': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Bárbara': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Catalina': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Cruz': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Cruz de Lorica': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Fe de Antioquia': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santafé de Bogotá': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Helena del Opón': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Isabel': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Lucía': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa María': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Marta (Dist. Esp.)': { zip_codes: ['00000'], nhcs_code: NaN },
    Santana: { zip_codes: ['00000'], nhcs_code: NaN },
    'Santander de Quilichao': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Rita': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Rosa': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Rosa de Cabal': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Rosa del Sur': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Rosa de Osos': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Rosa de Viterbo': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Rosalía': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santa Sofía': { zip_codes: ['00000'], nhcs_code: NaN },
    Santiago: { zip_codes: ['00000'], nhcs_code: NaN },
    'Santiago de Cali': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santo Domingo': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santo Domingo de Silos': { zip_codes: ['00000'], nhcs_code: NaN },
    'Santo Tomás': { zip_codes: ['00000'], nhcs_code: NaN },
    Santuario: { zip_codes: ['00000'], nhcs_code: NaN },
    'San Vicente': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Vicente de Chucurí': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Vicente del Caguán': { zip_codes: ['00000'], nhcs_code: NaN },
    'San Zenón': { zip_codes: ['00000'], nhcs_code: NaN },
    Sapuyes: { zip_codes: ['00000'], nhcs_code: NaN },
    Saravena: { zip_codes: ['00000'], nhcs_code: NaN },
    Sardinata: { zip_codes: ['00000'], nhcs_code: NaN },
    Sasaima: { zip_codes: ['00000'], nhcs_code: NaN },
    Sativanorte: { zip_codes: ['00000'], nhcs_code: NaN },
    Segovia: { zip_codes: ['00000'], nhcs_code: NaN },
    Sesquilé: { zip_codes: ['00000'], nhcs_code: NaN },
    Sevilla: { zip_codes: ['00000'], nhcs_code: NaN },
    Siachoque: { zip_codes: ['00000'], nhcs_code: NaN },
    Sibaté: { zip_codes: ['00000'], nhcs_code: NaN },
    Silvania: { zip_codes: ['00000'], nhcs_code: NaN },
    Silvia: { zip_codes: ['00000'], nhcs_code: NaN },
    Simacota: { zip_codes: ['00000'], nhcs_code: NaN },
    Simijaca: { zip_codes: ['00000'], nhcs_code: NaN },
    Simití: { zip_codes: ['00000'], nhcs_code: NaN },
    Sincé: { zip_codes: ['00000'], nhcs_code: NaN },
    Sincelejo: { zip_codes: ['00000'], nhcs_code: NaN },
    Sipí: { zip_codes: ['00000'], nhcs_code: NaN },
    Soacha: { zip_codes: ['00000'], nhcs_code: NaN },
    Soatá: { zip_codes: ['00000'], nhcs_code: NaN },
    Socha: { zip_codes: ['00000'], nhcs_code: NaN },
    Socorro: { zip_codes: ['00000'], nhcs_code: NaN },
    Socotá: { zip_codes: ['00000'], nhcs_code: NaN },
    Sogamoso: { zip_codes: ['00000'], nhcs_code: NaN },
    Solano: { zip_codes: ['00000'], nhcs_code: NaN },
    Soledad: { zip_codes: ['00000'], nhcs_code: NaN },
    Somondoco: { zip_codes: ['00000'], nhcs_code: NaN },
    Sonsón: { zip_codes: ['00000'], nhcs_code: NaN },
    Sopetrán: { zip_codes: ['00000'], nhcs_code: NaN },
    Soplaviento: { zip_codes: ['00000'], nhcs_code: NaN },
    Sopó: { zip_codes: ['00000'], nhcs_code: NaN },
    Sora: { zip_codes: ['00000'], nhcs_code: NaN },
    Soracá: { zip_codes: ['00000'], nhcs_code: NaN },
    Sotaquirá: { zip_codes: ['00000'], nhcs_code: NaN },
    Sotará: { zip_codes: ['00000'], nhcs_code: NaN },
    Suaita: { zip_codes: ['00000'], nhcs_code: NaN },
    Suan: { zip_codes: ['00000'], nhcs_code: NaN },
    Suárez: { zip_codes: ['00000'], nhcs_code: NaN },
    Suaza: { zip_codes: ['00000'], nhcs_code: NaN },
    Subachoque: { zip_codes: ['00000'], nhcs_code: NaN },
    Sucre: { zip_codes: ['00000'], nhcs_code: NaN },
    Suesca: { zip_codes: ['00000'], nhcs_code: NaN },
    Supatá: { zip_codes: ['00000'], nhcs_code: NaN },
    Supía: { zip_codes: ['00000'], nhcs_code: NaN },
    Suratá: { zip_codes: ['00000'], nhcs_code: NaN },
    Susa: { zip_codes: ['00000'], nhcs_code: NaN },
    Susacón: { zip_codes: ['00000'], nhcs_code: NaN },
    Sutamarchán: { zip_codes: ['00000'], nhcs_code: NaN },
    Sutatausa: { zip_codes: ['00000'], nhcs_code: NaN },
    Sutatenza: { zip_codes: ['00000'], nhcs_code: NaN },
    Tabio: { zip_codes: ['00000'], nhcs_code: NaN },
    Tadó: { zip_codes: ['00000'], nhcs_code: NaN },
    'Talaigua Nuevo': { zip_codes: ['00000'], nhcs_code: NaN },
    Tamalameque: { zip_codes: ['00000'], nhcs_code: NaN },
    Támara: { zip_codes: ['00000'], nhcs_code: NaN },
    Tame: { zip_codes: ['00000'], nhcs_code: NaN },
    Támesis: { zip_codes: ['00000'], nhcs_code: NaN },
    Taminango: { zip_codes: ['00000'], nhcs_code: NaN },
    Tangua: { zip_codes: ['00000'], nhcs_code: NaN },
    Taraira: { zip_codes: ['00000'], nhcs_code: NaN },
    Tarapacá: { zip_codes: ['00000'], nhcs_code: NaN },
    Tarazá: { zip_codes: ['00000'], nhcs_code: NaN },
    Tarquí: { zip_codes: ['00000'], nhcs_code: NaN },
    Tarso: { zip_codes: ['00000'], nhcs_code: NaN },
    Tasco: { zip_codes: ['00000'], nhcs_code: NaN },
    Tauramena: { zip_codes: ['00000'], nhcs_code: NaN },
    Tausa: { zip_codes: ['00000'], nhcs_code: NaN },
    Tello: { zip_codes: ['00000'], nhcs_code: NaN },
    Tena: { zip_codes: ['00000'], nhcs_code: NaN },
    Tenerife: { zip_codes: ['00000'], nhcs_code: NaN },
    Tenjo: { zip_codes: ['00000'], nhcs_code: NaN },
    Tenza: { zip_codes: ['00000'], nhcs_code: NaN },
    Teorama: { zip_codes: ['00000'], nhcs_code: NaN },
    Teruel: { zip_codes: ['00000'], nhcs_code: NaN },
    Tesalia: { zip_codes: ['00000'], nhcs_code: NaN },
    Tibacuy: { zip_codes: ['00000'], nhcs_code: NaN },
    Tibaná: { zip_codes: ['00000'], nhcs_code: NaN },
    Tibasosa: { zip_codes: ['00000'], nhcs_code: NaN },
    Tibirita: { zip_codes: ['00000'], nhcs_code: NaN },
    Tibú: { zip_codes: ['00000'], nhcs_code: NaN },
    Tierralta: { zip_codes: ['00000'], nhcs_code: NaN },
    Timaná: { zip_codes: ['00000'], nhcs_code: NaN },
    Timbío: { zip_codes: ['00000'], nhcs_code: NaN },
    Timbiquí: { zip_codes: ['00000'], nhcs_code: NaN },
    Tinjacá: { zip_codes: ['00000'], nhcs_code: NaN },
    Titiribí: { zip_codes: ['00000'], nhcs_code: NaN },
    Toca: { zip_codes: ['00000'], nhcs_code: NaN },
    Tocaima: { zip_codes: ['00000'], nhcs_code: NaN },
    Tocancipá: { zip_codes: ['00000'], nhcs_code: NaN },
    Toguí: { zip_codes: ['00000'], nhcs_code: NaN },
    Toledo: { zip_codes: ['00000'], nhcs_code: NaN },
    Tolú: { zip_codes: ['00000'], nhcs_code: NaN },
    Toluviejo: { zip_codes: ['00000'], nhcs_code: NaN },
    Tona: { zip_codes: ['00000'], nhcs_code: NaN },
    Topagá: { zip_codes: ['00000'], nhcs_code: NaN },
    Topaipí: { zip_codes: ['00000'], nhcs_code: NaN },
    Toribío: { zip_codes: ['00000'], nhcs_code: NaN },
    Toro: { zip_codes: ['00000'], nhcs_code: NaN },
    Tota: { zip_codes: ['00000'], nhcs_code: NaN },
    Totoró: { zip_codes: ['00000'], nhcs_code: NaN },
    Trinidad: { zip_codes: ['00000'], nhcs_code: NaN },
    Trujillo: { zip_codes: ['00000'], nhcs_code: NaN },
    Tubará: { zip_codes: ['00000'], nhcs_code: NaN },
    Tuluá: { zip_codes: ['00000'], nhcs_code: NaN },
    Tumaco: { zip_codes: ['00000'], nhcs_code: NaN },
    Tunja: { zip_codes: ['00000'], nhcs_code: NaN },
    Tunungua: { zip_codes: ['00000'], nhcs_code: NaN },
    Túquerres: { zip_codes: ['00000'], nhcs_code: NaN },
    Turbaco: { zip_codes: ['00000'], nhcs_code: NaN },
    Turbaná: { zip_codes: ['00000'], nhcs_code: NaN },
    Turbo: { zip_codes: ['00000'], nhcs_code: NaN },
    Tuta: { zip_codes: ['00000'], nhcs_code: NaN },
    Tutazá: { zip_codes: ['00000'], nhcs_code: NaN },
    Ubalá: { zip_codes: ['00000'], nhcs_code: NaN },
    Ubaque: { zip_codes: ['00000'], nhcs_code: NaN },
    Ulloa: { zip_codes: ['00000'], nhcs_code: NaN },
    Umbita: { zip_codes: ['00000'], nhcs_code: NaN },
    Une: { zip_codes: ['00000'], nhcs_code: NaN },
    Unguía: { zip_codes: ['00000'], nhcs_code: NaN },
    Uramita: { zip_codes: ['00000'], nhcs_code: NaN },
    Uribia: { zip_codes: ['00000'], nhcs_code: NaN },
    Urrao: { zip_codes: ['00000'], nhcs_code: NaN },
    Urumita: { zip_codes: ['00000'], nhcs_code: NaN },
    Usiacurí: { zip_codes: ['00000'], nhcs_code: NaN },
    Utica: { zip_codes: ['00000'], nhcs_code: NaN },
    Valdivia: { zip_codes: ['00000'], nhcs_code: NaN },
    Valencia: { zip_codes: ['00000'], nhcs_code: NaN },
    'Valle del Guamuez': { zip_codes: ['00000'], nhcs_code: NaN },
    'Valle de San José': { zip_codes: ['00000'], nhcs_code: NaN },
    'Valle de San Juan': { zip_codes: ['00000'], nhcs_code: NaN },
    Valledupar: { zip_codes: ['00000'], nhcs_code: NaN },
    Valparaíso: { zip_codes: ['00000'], nhcs_code: NaN },
    Vegachí: { zip_codes: ['00000'], nhcs_code: NaN },
    Vélez: { zip_codes: ['00000'], nhcs_code: NaN },
    Venadillo: { zip_codes: ['00000'], nhcs_code: NaN },
    Venecia: { zip_codes: ['00000'], nhcs_code: NaN },
    Ventaquemada: { zip_codes: ['00000'], nhcs_code: NaN },
    Vergara: { zip_codes: ['00000'], nhcs_code: NaN },
    Versalles: { zip_codes: ['00000'], nhcs_code: NaN },
    Vetas: { zip_codes: ['00000'], nhcs_code: NaN },
    Vianí: { zip_codes: ['00000'], nhcs_code: NaN },
    Victoria: { zip_codes: ['00000'], nhcs_code: NaN },
    'Vigía del Fuerte': { zip_codes: ['00000'], nhcs_code: NaN },
    Vijes: { zip_codes: ['00000'], nhcs_code: NaN },
    'Villa Caro': { zip_codes: ['00000'], nhcs_code: NaN },
    'Villa de Leyva': { zip_codes: ['00000'], nhcs_code: NaN },
    'Villa del Rosario': { zip_codes: ['00000'], nhcs_code: NaN },
    'Villa de San Diego de Ubaté': { zip_codes: ['00000'], nhcs_code: NaN },
    Villagarzón: { zip_codes: ['00000'], nhcs_code: NaN },
    Villagómez: { zip_codes: ['00000'], nhcs_code: NaN },
    Villahermosa: { zip_codes: ['00000'], nhcs_code: NaN },
    Villamaría: { zip_codes: ['00000'], nhcs_code: NaN },
    Villanueva: { zip_codes: ['00000'], nhcs_code: NaN },
    Villapinzón: { zip_codes: ['00000'], nhcs_code: NaN },
    Villarrica: { zip_codes: ['00000'], nhcs_code: NaN },
    Villavicencio: { zip_codes: ['00000'], nhcs_code: NaN },
    Villavieja: { zip_codes: ['00000'], nhcs_code: NaN },
    Villeta: { zip_codes: ['00000'], nhcs_code: NaN },
    Viotá: { zip_codes: ['00000'], nhcs_code: NaN },
    Viracachá: { zip_codes: ['00000'], nhcs_code: NaN },
    'Vista Hermosa': { zip_codes: ['00000'], nhcs_code: NaN },
    Viterbo: { zip_codes: ['00000'], nhcs_code: NaN },
    Yacopí: { zip_codes: ['00000'], nhcs_code: NaN },
    Yacuanquer: { zip_codes: ['00000'], nhcs_code: NaN },
    Yaguará: { zip_codes: ['00000'], nhcs_code: NaN },
    Yalí: { zip_codes: ['00000'], nhcs_code: NaN },
    Yarumal: { zip_codes: ['00000'], nhcs_code: NaN },
    Yavaraté: { zip_codes: ['00000'], nhcs_code: NaN },
    Yolombó: { zip_codes: ['00000'], nhcs_code: NaN },
    Yondó: { zip_codes: ['00000'], nhcs_code: NaN },
    Yopal: { zip_codes: ['00000'], nhcs_code: NaN },
    Yotoco: { zip_codes: ['00000'], nhcs_code: NaN },
    Yumbo: { zip_codes: ['00000'], nhcs_code: NaN },
    Zambrano: { zip_codes: ['00000'], nhcs_code: NaN },
    Zapatoca: { zip_codes: ['00000'], nhcs_code: NaN },
    Zaragoza: { zip_codes: ['00000'], nhcs_code: NaN },
    Zarzal: { zip_codes: ['00000'], nhcs_code: NaN },
    Zetaquirá: { zip_codes: ['00000'], nhcs_code: NaN },
    Zipacón: { zip_codes: ['00000'], nhcs_code: NaN },
    Zipaquirá: { zip_codes: ['00000'], nhcs_code: NaN }
  },
  tz: { county: { zip_codes: ['00000'], nhcs_code: NaN } }
}
