/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response shape for POST /api/adequacies/
 */
export type PostAdequaciesResponse = {
  id: number
  /**
   * Distance (in miles) to the closest provider
   */
  distance_to_closest_provider: number
  /**
   * Time (in minutes) to the closest provider
   */
  time_to_closest_provider: number
  closest_provider_by_distance: {latitude: number, longitude: number}
  closest_provider_by_time: {latitude: number, longitude: number}
}[]
