/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response shape for POST /api/geocode/
 */
export type PostGeocodeResponse = (Success | Error)[]

export interface Success {
  status: 'success'
  lat: number
  lng: number
}
export interface Error {
  status: 'error'
  message: string
}
