/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Request shape for POST /api/providers/
 */
export interface PostProvidersRequest {
  providers: {
    /**
     * Excluding suite #.
     * Eg. "1234 Main St. San Francisco, CA 94114"
     */
    address: string
    /**
     * Eg. ["Burmese", "Chinese", "Spanish"]
     */
    languages: string[]
    /**
     * Unique 10-digit gov't ID assigned to each healthcare provider
     */
    npi: number
    /**
     * Eg. "Internal Medicine"
     */
    specialty?: string
  }[]
}
