/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dummy 'response' shape for static representative points
 */
export type StaticRepresentativePointsResponse = {
  county: string
  id: number
  lat: number
  lng: number
  population: number
  service_area_id: string
  zip: string
}[]
